swagger: '2.0'
info:
  title: HTTP API Console ABCI Evidence API
  name: ''
  description: ABCI APIs
tags:
- name: Evidence
  description: Evidence APIs
paths:
  /broadcast_evidence:
    get:
      summary: Broadcast evidence of the misbehavior.
      operationId: broadcast_evidence
      parameters:
      - in: query
        name: evidence
        description: JSON evidence
        required: true
        schema:
          type: string
          example: JSON_EVIDENCE_encoded
      tags:
      - Evidence
      description: 'Broadcast evidence of the misbehavior.

        '
      responses:
        '200':
          description: Broadcast evidence of the misbehavior.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BroadcastEvidenceResponse'
        '500':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    JSONRPC:
      type: object
      properties:
        id:
          type: integer
          example: 0
        jsonrpc:
          type: string
          example: '2.0'
    BroadcastEvidenceResponse:
      type: object
      required:
      - id
      - jsonrpc
      properties:
        error:
          type: string
          example: ''
        result:
          type: string
          example: ''
        id:
          type: integer
          example: 0
        jsonrpc:
          type: string
          example: '2.0'
    ErrorResponse:
      description: Error Response
      allOf:
      - $ref: '#/components/schemas/JSONRPC'
      - type: object
        properties:
          error:
            type: string
            example: Description of failure
